# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1e5c9b1319eda9e98b4d02c436f93ff5e1ada32fc994210569a87ff1d39ce5d9e295341206abca9e16844ecc90dffa9e1a5ed5fd994749dfee3ed1dc8e2a52b

test:
  secret_key_base: cbe2a8711fb10c23177370f7e3a44bc65a36e8f940b199d1e4c906d919a506484a114f6f89d6138ece5df92ac947ea498d683e10c5a224cbf917231b54d51155

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
